### ISSUE TITLE
Design library gets rendered only partly

### ISSUE THREAD

**Issue by TopperDEL** [mrbeam/OctoPrint#54] opened 2015-11-23 20:17 UTC
There seems to be an issue within the latest version. The design library is cut off on top and bottom, so I can't see the full list. It show wrong in IE, Edge and Chrome.
<img width="715" alt="error" src="https://cloud.githubusercontent.com/assets/1833242/11348598/a0b85a60-9227-11e5-9d68-bb716d73b67a.png">

**Comment by TopperDEL** [comment] 2015-11-24 18:16
I realized this only happens when I'm logged in.

**Comment by mrbeam** [comment] 2015-11-25 09:30
damn, this is ugly. Reason: your username is too long and causing the whole menu to wrap to the next line. 
Workaround until fix:  use a shorter username.

**Comment by TopperDEL** [comment] 2015-11-25 09:32
I think I go for "Mr.T"... :)

**Comment by make-ing** [comment] 2016-06-16 08:49
I can't reproduce it, and i think this was fixed with the commit 43a476e. If you still have problems please comment again and i will reopen this issue. Until then, fixed!

**Comment by make-ing** [comment] 2016-06-20 10:05
The problem is still present and seems to be font related. Which OS are you using? Windows?

**Comment by amrsoll** [comment] 2020-01-09 13:30
Is fixed in the plugin now

**Closed by amrsoll** 2020-01-09 13:30 UTC
Labels: bug
