### ISSUE TITLE
Support for dashed lines

### ISSUE THREAD

**Issue by mrbeam** [mrbeam/OctoPrint#24] opened 2015-05-27 12:18 UTC
e.g.:

``` xml
   <path stroke-dasharray="20,10,5,5,5,10" d="M5 60 l215 0" />
```

**Comment by amrsoll** [comment] 2020-01-09 13:24
Duplicate of mrbeam/MrBeamPlugin#238

**Closed by amrsoll** 2020-01-09 13:24 UTC
Labels: enhancement
